apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kiam-server-certificate
  namespace: kube-system
spec:
  secretName: kiam-server-certificate-secret
  issuerRef:
    name: self-signed-certificate-issuer
    kind: Issuer
  commonName: kiam-server
  dnsNames:
    - kiam-server
    - localhost
  ipAddresses:
    - 127.0.0.1
  renewBefore: 360h # 15d
